Repository Excosist/Creativity, pull requests merged in 2022-10, with the labels that each got.

#2 Coding=Magic
  AppBreweryWallpaper.jpg
Labels: hactoberfest

#3 added
  photo-1537444399873-da0fea0cf4b3.jfif
Labels: hactoberfest

#8 C code
  palindrome.cpp
Labels: hactoberfest, hactoberfest-accepted

#9 c++
  plus-one.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#10 3
  sqrt1.cpp
Labels: hacktoberfest, hacktoberfest-accepted
